### ISSUE TITLE
Server upload and authentication not done.

### ISSUE THREAD

**Issue by Dazz10** [Tech-Makers/CDS#1]
After clicking pictures, we have to upload it to the AWS S3 bucket otherwise our algorithm will be unable to fetch data from the S3 bucket.

**Comment by Tanmoy2Sau** [comment]
We are updating the code, we will complete it very soon.

**Comment by Vshree61** [comment]
We have rectified this issue ,now the captured images are getting uploaded to AWS s3 bucket. Please verify this issue @dazz10 and close it.

**Comment by dazz10** [comment]
Authentation Done and Verified

**Comment by Dazz10** [comment]
Authetication Done and Verified
